services:
  - type: web
    name: academio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd /opt/render/project/src && gunicorn --chdir AcademioProject AcademioProject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SETTINGS_MODULE
        value: "AcademioProject.settings" 