services:
  - type: web
    name: academio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn AcademioProject.wsgi:application --log-file -"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SETTINGS_MODULE
        value: "AcademioProject.settings"
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 