# Generated by Django 5.1 on 2024-12-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagemanage.people')),
                ('grade', models.IntegerField()),
            ],
            bases=('pagemanage.people',),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagemanage.people')),
                ('branch', models.CharField(max_length=30)),
                ('numberOfClasses', models.IntegerField()),
            ],
            bases=('pagemanage.people',),
        ),
    ]
